server:
  servlet:
    context-path: /documenti
  port: 8101

---
#configurazione ambiente locale
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ENC(MUJKfPnoFkVkPVg+XFdHob4sAEfDI8kIMLwb+bRupVv4qv76JQy7f6YrpCyDJwTu+RwkutVyAgQ=)
    username: ENC(2e9Gx+QJBartl2xIDrBXIRo5WOzUQ91V)
    password: ENC(pxSpC9lRD6mNueouzFPwOPWBisaNf9fi)
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true

---
#configurazione ambiente sviluppo
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:oracle:thin:@192.168.22.20:1521/orclpdbssdsvil.ced.local
    username: acnpgm01
    password: acnpgm01
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
